import { BadGatewayException, BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import axios from 'axios';
import * as archiver from 'archiver';
import { PassThrough } from 'stream';
import { ProjectStatus, StageStatus } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { STAGE_LABELS, STAGE_ORDER } from '../common/stage-order';
import { CreateProjectDto } from './dto/create-project.dto';

const ARTIFACT_FILE_NAMES: Record<string, string> = {
  PRD: 'prd.md',
  ARCHITECTURE: 'architecture.yaml',
  ESTIMATION: 'estimation.yaml',
  DATABASE: 'database.sql',
  BACKEND: 'backend-source-summary.txt',
  FRONTEND: 'frontend-source-summary.txt',
  QA: 'qa-report.md',
  PACKAGE: 'project-manifest.json',
};

@Injectable()
export class ProjectsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly config: ConfigService,
  ) {}

  // V1.1.1: setiap project harus punya ownerId — diambil dari JWT user yang membuat, BUKAN
  // dari body request (jangan pernah percaya client bisa memilih siapa pemiliknya sendiri).
  async create(dto: CreateProjectDto, ownerId: string) {
    const project = await this.prisma.project.create({
      data: {
        name: dto.name,
        businessIdea: dto.businessIdea,
        knowledgeBaseId: dto.knowledgeBaseId,
        aiModel: dto.aiModel ?? 'gpt-5-mini',
        ownerId,
        stages: {
          create: STAGE_ORDER.map((stageKey) => ({ stageKey, status: StageStatus.PENDING })),
        },
      },
      include: { stages: true },
    });

    const webhookUrl = this.config.get<string>('N8N_START_WEBHOOK_URL');
    try {
      await axios.post(webhookUrl as string, {
        projectId: project.id,
        businessIdea: project.businessIdea,
        knowledgeBaseId: project.knowledgeBaseId,
        aiModel: project.aiModel,
        userId: ownerId,
      });
    } catch (err) {
      throw new BadGatewayException(
        `Project dibuat, tapi gagal memicu workflow n8n: ${(err as Error).message}`,
      );
    }

    return this.withCurrentStage(project);
  }

  // V1.1.1: HANYA project milik user ini — bukan semua project di database.
  async findAll(ownerId: string) {
    const projects = await this.prisma.project.findMany({
      where: { ownerId },
      include: { stages: true },
      orderBy: { createdAt: 'desc' },
    });
    return projects.map((p) => this.withCurrentStage(p));
  }

  // V1.1.1: where: { id, ownerId } sekaligus — kalau project ada tapi bukan milik user ini,
  // hasilnya SAMA seperti project tidak ada (404), bukan 403. Ini sengaja: tidak membocorkan
  // informasi "project ini ada tapi bukan milikmu" ke user yang tidak berhak.
  async findOne(id: string, ownerId: string) {
    const project = await this.prisma.project.findFirst({
      where: { id, ownerId },
      include: { stages: true },
    });
    if (!project) throw new NotFoundException('Project tidak ditemukan');

    const stages = STAGE_ORDER.map((stageKey) => {
      const stage = project.stages.find((s) => s.stageKey === stageKey);
      return {
        stageKey,
        label: STAGE_LABELS[stageKey],
        status: stage?.status ?? StageStatus.PENDING,
        artifactName: stage?.artifactName ?? null,
        content: stage?.content ?? null,
        comment: stage?.comment ?? null,
        decidedBy: stage?.decidedBy ?? null,
        generatedAt: stage?.generatedAt ?? null,
        decidedAt: stage?.decidedAt ?? null,
      };
    });

    return {
      id: project.id,
      name: project.name,
      businessIdea: project.businessIdea,
      knowledgeBaseId: project.knowledgeBaseId,
      aiModel: project.aiModel,
      status: project.status,
      createdAt: project.createdAt,
      updatedAt: project.updatedAt,
      stages,
    };
  }

  async buildDownloadArchive(id: string, ownerId: string): Promise<PassThrough> {
    const project = await this.prisma.project.findFirst({
      where: { id, ownerId },
      include: { stages: true },
    });
    if (!project) throw new NotFoundException('Project tidak ditemukan');

    if (project.status !== ProjectStatus.COMPLETED) {
      throw new BadRequestException(
        `Project belum selesai (status saat ini: ${project.status}). Download hanya tersedia setelah status COMPLETED.`,
      );
    }

    const archive = archiver('zip', { zlib: { level: 9 } });
    const output = new PassThrough();
    archive.on('error', (err) => output.destroy(err));
    archive.pipe(output);

    for (const stageKey of STAGE_ORDER) {
      const stage = project.stages.find((s) => s.stageKey === stageKey);
      if (!stage?.content) continue;
      const fileName = ARTIFACT_FILE_NAMES[stageKey] ?? `${stageKey.toLowerCase()}.txt`;
      archive.append(stage.content, { name: fileName });
    }

    archive.append(
      [
        `# ${project.name}`,
        '',
        `Generated by AI Software Factory — project ${project.id}`,
        `Status: ${project.status}`,
        `Updated: ${project.updatedAt.toISOString()}`,
      ].join('\n'),
      { name: 'README.md' },
    );

    await archive.finalize();
    return output;
  }

  private withCurrentStage(project: { stages: { stageKey: string; status: StageStatus }[] } & Record<string, any>) {
    const currentStage =
      STAGE_ORDER.find((key) => {
        const stage = project.stages.find((s: any) => s.stageKey === key);
        return !stage || stage.status !== StageStatus.APPROVED;
      }) ?? null;

    return {
      id: project.id,
      name: project.name,
      businessIdea: project.businessIdea,
      status: project.status,
      createdAt: project.createdAt,
      updatedAt: project.updatedAt,
      currentStage,
      currentStageLabel: currentStage ? STAGE_LABELS[currentStage] : 'Selesai',
    };
  }
}
